-- Chạy một lần bằng ACCOUNTADMIN để tạo tài nguyên và role tối thiểu.
-- Sau bước này pipeline hằng ngày KHÔNG dùng ACCOUNTADMIN.
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS SUPERSTORE_DB;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS SUPERSTORE_LOADER_ROLE;
CREATE ROLE IF NOT EXISTS SUPERSTORE_DBT_ROLE;

CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.BRONZE_LAYER;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.ANALYTIC_LAYER;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.ANALYTIC_LAYER_STAGING_LAYER;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.ANALYTIC_LAYER_SILVER_LAYER;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.ANALYTIC_LAYER_GOLD_LAYER;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.ANALYTIC_LAYER_MART_LAYER;
CREATE SCHEMA IF NOT EXISTS SUPERSTORE_DB.DBT_SNAPSHOTS;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SUPERSTORE_LOADER_ROLE;
GRANT USAGE ON DATABASE SUPERSTORE_DB TO ROLE SUPERSTORE_LOADER_ROLE;
GRANT USAGE, CREATE TABLE ON SCHEMA SUPERSTORE_DB.BRONZE_LAYER
    TO ROLE SUPERSTORE_LOADER_ROLE;
GRANT SELECT, INSERT
    ON ALL TABLES IN SCHEMA SUPERSTORE_DB.BRONZE_LAYER
    TO ROLE SUPERSTORE_LOADER_ROLE;
GRANT SELECT, INSERT
    ON FUTURE TABLES IN SCHEMA SUPERSTORE_DB.BRONZE_LAYER
    TO ROLE SUPERSTORE_LOADER_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE ON DATABASE SUPERSTORE_DB TO ROLE SUPERSTORE_DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE SUPERSTORE_DB TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE ON SCHEMA SUPERSTORE_DB.BRONZE_LAYER TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER
    TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_STAGING_LAYER
    TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_SILVER_LAYER
    TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_GOLD_LAYER
    TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_MART_LAYER
    TO ROLE SUPERSTORE_DBT_ROLE;
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA SUPERSTORE_DB.DBT_SNAPSHOTS
    TO ROLE SUPERSTORE_DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SUPERSTORE_DB.BRONZE_LAYER
    TO ROLE SUPERSTORE_DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPERSTORE_DB.BRONZE_LAYER
    TO ROLE SUPERSTORE_DBT_ROLE;

-- Gán role cho user Snowflake đang được pipeline sử dụng.
-- GRANT ROLE có thể chạy lại an toàn khi khởi tạo môi trường.
GRANT ROLE SUPERSTORE_LOADER_ROLE TO USER PHU;
GRANT ROLE SUPERSTORE_DBT_ROLE TO USER PHU;

SHOW ROLES LIKE 'SUPERSTORE_%';
SHOW GRANTS TO USER PHU;
