USE ROLE ACCOUNTADMIN;

SET app_user = 'SUPERSTORE_API_USER';

CREATE ROLE IF NOT EXISTS ANALYTICS_READONLY;

-- Tạo dedicated user cho API trước khi cấp role.
-- Không hard-code PASSWORD trong file Git. Sau khi chạy script, ACCOUNTADMIN phải đặt
-- password một lần bằng ALTER USER hoặc Snowsight rồi lưu cùng giá trị vào RAG_CHATBOT/.env.
CREATE USER IF NOT EXISTS IDENTIFIER($app_user)
    LOGIN_NAME = 'SUPERSTORE_API_USER'
    DISPLAY_NAME = 'Superstore API Service User'
    DEFAULT_WAREHOUSE = COMPUTE_WH
    DEFAULT_NAMESPACE = 'SUPERSTORE_DB.ANALYTIC_LAYER_MART_LAYER'
    DEFAULT_ROLE = ANALYTICS_READONLY
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Read-only service user for the Superstore analytics API';

GRANT USAGE
ON WAREHOUSE COMPUTE_WH
TO ROLE ANALYTICS_READONLY;

GRANT USAGE
ON DATABASE SUPERSTORE_DB
TO ROLE ANALYTICS_READONLY;

GRANT USAGE
ON SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_GOLD_LAYER
TO ROLE ANALYTICS_READONLY;

GRANT USAGE
ON SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_MART_LAYER
TO ROLE ANALYTICS_READONLY;

GRANT SELECT
ON ALL TABLES IN SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_GOLD_LAYER
TO ROLE ANALYTICS_READONLY;

GRANT SELECT
ON ALL TABLES IN SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_MART_LAYER
TO ROLE ANALYTICS_READONLY;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_GOLD_LAYER
TO ROLE ANALYTICS_READONLY;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA SUPERSTORE_DB.ANALYTIC_LAYER_MART_LAYER
TO ROLE ANALYTICS_READONLY;

GRANT ROLE ANALYTICS_READONLY
TO USER IDENTIFIER($app_user);

SHOW USERS LIKE 'SUPERSTORE_API_USER';
SHOW GRANTS TO USER IDENTIFIER($app_user);
SHOW GRANTS TO ROLE ANALYTICS_READONLY;
